spring:
  # 数据源配置
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/it_cloud?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

logging:
  config: classpath:it-logback.xml
  path: ~/Download/log
  #打印sql
  level:
    com.it.cloud.modules: debug

  # redis 配置
  redis:
    host: localhost
    port: 6379
    database: 0
    password:    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
#    lettuce:   #多线程客户端
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

