spring:
  # 数据源配置
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/helloworld?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&nullCatalogMeansCurrent=true
    username: root
    password: root

logging:
  config: classpath:rename-logback.xml
  path: ~/Download/log
  #打印sql
  level:
    com.it.cloud.modules: debug

